// Generated by tools/multiview/twin.py. Do not edit.
//
// Every piece the catalogue has from a photograph rather than from a mesh. Six
// fixed views each, because six is what Zero123++ emits - one 640x960 grid of
// 320px tiles, at azimuths 30/90/150/210/270/330. There is no elevation axis and
// no seventh view to be had.

export interface GeneratedTwin {
  slug: string;
  id: string;
  name: string;
  wornOn: "ears" | "finger" | "neck";
  /** How wide the piece really is. A photograph carries no scale of its own. */
  widthMm: number;
  views: number;
  note: string;
}

export const GENERATED_TWINS: GeneratedTwin[] = [
  { slug: "heart-vine-ring", id: "R-2201", name: "Heart Vine Ring", wornOn: "finger", widthMm: 21.0, note: "Built from one photograph, so it turns in 60 degree steps and keeps its own metal.", views: 6 },
  { slug: "rose-halo-stud", id: "E-3310", name: "Rose Halo Stud", wornOn: "ears", widthMm: 9.0, note: "Built from one photograph, so it turns in 60 degree steps and keeps its own metal.", views: 6 },
];
