// Generated by tools/tryon/build-worn.py. Do not edit.
//
// What the camera needs to know about each cut-out: how many views of the piece
// there are, and what the whole square of one view is worth in millimetres. The
// second is not the width of the piece - it is the piece plus the transparent
// margin squaring the crop added, which is what a draw call actually scales.

export interface WornEntry {
  frames: number;
  frameMm: number;
}

export const WORN: Record<string, Record<string, WornEntry>> = {
  earring: {
    "rose-emerald": { frames: 24, frameMm: 9.0 },
    "rose-natural": { frames: 24, frameMm: 9.0 },
    "rose-ruby": { frames: 24, frameMm: 9.0 },
    "white-emerald": { frames: 24, frameMm: 9.0 },
    "white-natural": { frames: 24, frameMm: 9.0 },
    "white-ruby": { frames: 24, frameMm: 9.0 },
    "yellow-emerald": { frames: 24, frameMm: 9.0 },
    "yellow-natural": { frames: 24, frameMm: 9.0 },
    "yellow-ruby": { frames: 24, frameMm: 9.0 },
  },
  necklace: {
    "rose-emerald": { frames: 24, frameMm: 26.97 },
    "rose-natural": { frames: 24, frameMm: 26.97 },
    "rose-ruby": { frames: 24, frameMm: 26.97 },
    "white-emerald": { frames: 24, frameMm: 26.97 },
    "white-natural": { frames: 24, frameMm: 26.97 },
    "white-ruby": { frames: 24, frameMm: 26.97 },
    "yellow-emerald": { frames: 24, frameMm: 26.97 },
    "yellow-natural": { frames: 24, frameMm: 26.97 },
    "yellow-ruby": { frames: 24, frameMm: 26.97 },
  },
  ring: {
    "rose-emerald": { frames: 24, frameMm: 19.0 },
    "rose-natural": { frames: 24, frameMm: 19.0 },
    "rose-ruby": { frames: 24, frameMm: 19.0 },
    "white-emerald": { frames: 24, frameMm: 19.0 },
    "white-natural": { frames: 24, frameMm: 19.0 },
    "white-ruby": { frames: 24, frameMm: 19.0 },
    "yellow-emerald": { frames: 24, frameMm: 19.0 },
    "yellow-natural": { frames: 24, frameMm: 19.0 },
    "yellow-ruby": { frames: 24, frameMm: 19.0 },
  },
};
